### PR TITLE
chore: adjust to make install M1 compatible

### PR DESCRIPTION
**Pull request by dkam**
Update the ext code to look in the new Homebrew path on M1

### CODE REVIEW

**Comment by aledalgrande** [comment]
Is there any blocker to getting this PR merged? Thanks

**Comment by westonplatter** [comment]
Naive question, @aledalgrande what happens for linux users if `opt/homebrew/lib` does not exist?

**Comment by westonplatter** [comment]
The library isn't setup to test PRs at this point, so this hasn't been automatically tested within Travis CI, https://travis-ci.org/github/westonplatter/phashion/branches.

**Comment by aledalgrande** [comment]
Interesting I thought Travis would build branches by default. Your conf doesn't exclude branches.

**Comment by aledalgrande** [comment]
Oh wait it does: https://travis-ci.org/github/westonplatter/phashion/pull_requests

**Comment by westonplatter** [comment]
Score. I don't see a CI Test Suite run for this PR. My guess is the integration needs to get looked at. Any ideas?

**Comment by westonplatter** [comment]
yep. Might be a day or two (tied up at work).

**Comment by aledalgrande** [comment]
Hey, no worries if you don't have time, but just checking back to put this on your radar.

**Pull request closed without merging**
