### PR TITLE
Add dupe check passing two fingerprints

### PR DESCRIPTION
**Pull request by gallois**
In my scenario, I save the fingerprints and check for dupes sometime in the future.

I thought that a module method for that would do the trick.

### CODE REVIEW

**Comment by asianfilm** [comment]
I really appreciated the addition you made to the gem, @gallois; I hope it gets pulled in.

**Comment by MadBomber** [comment]
This is also a feature that I can use.

**Comment by westonplatter** [comment]
Hey @gallois. Sorry I've left this hanging for so long. Thanks for the PR 👍. 

I can understand the desire to add the module method. I'l take a look at it this weekend and work on moving it into the gem.

**Comment by westonplatter** [comment]
@gallois thanks for the pull request!

**Pull request merged**
